import "./globals.css";
import "./ui-editor/style.css";

import { Inter } from "next/font/google";
import { headers, cookies } from "next/headers";
import { Providers } from "./providers";
import { ApiHandler } from "./lib-auth";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: React.PropsWithChildren) {
  // TODO auto sign in in server side
  // const result = await ApiHandler.authWithGuestUser(request as any as Request);

  const session = await ApiHandler.session();

  return (
    <html lang="en" className="light">
      <body>
        <Providers session={session}>{props.children}</Providers>
      </body>
    </html>
  );
}
